CREATE DATABASE IF NOT EXISTS catalogo_web;
USE catalogo_web;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  description TEXT NOT NULL,
  brand VARCHAR(100),
  img TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE
);
